version: "3.8"
services:
  backend: 
    build: ./be
    ports:
      - "9092:4000"
    volumes:
      - ./be:/src/app
      - /src/app/node_modules
    restart: unless-stopped

  frontendadmin:
    build: ./Admin
    ports:
      - "9090:5170"
    volumes:
      - ./Admin:/src/app
      - /src/app/node_modules
    restart: unless-stopped

  frontenduser:
    build: ./fe
    ports:
      - "9091:5173"
    volumes:
      - ./fe:/src/app
      - /src/app/node_modules
    restart: unless-stopped
