# FROM node:18

# WORKDIR /src/app

# COPY package*.json ./

# RUN npm install

# COPY . .

# EXPOSE 5173

# CMD ["npm","run","dev","--","--port","5173"]
# Stage 1: Build the Vite app
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install               
COPY . .                      
RUN npx vite build              

# Stage 2: Nginx to serve the built files
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html    
COPY nginx.conf /etc/nginx/conf.d/default.conf       
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]