server {
    listen 80;
    server_name localhost;
    root /var/www/smartconf/user;
    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    
    # User FE
    location /user/ {
        index index.html;
        try_files $uri $uri/ /index.html;
    }

}
