server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Serve Admin SPA on any /admin/* path
    location / {
        # Serve files from the web root (where dist is copied)
        try_files $uri $uri/ /index.html;
    }
    
}